<html>
<head>
    <title>{{ $file_name }}</title>
    <style>
        table {
            white-space: nowrap;
            font-size: 12px;
        }

        @media print {
            .table{
                border-collapse: collapse;
            }
    
            .table tr td{
                border: 1px solid #ccc;
                padding: 5px;
               
            }
    
            .table tr:last-child td{
                border: 1px solid white;
            } 
        }

        header {
                position: fixed;
                top: -60px;
                left: 0px;
                right: 0px;
                height: 50px;

                /** Extra personal styles **/
                background-color: #AE292F;
                color: white;
                text-align: center;
                line-height: 35px;
            }

            footer {
                position: fixed; 
                bottom: -60px; 
                left: 0px; 
                right: 0px;
                height: 50px; 

                /** Extra personal styles **/
                background-color: #AE292F;
                color: white;
                text-align: center;
                line-height: 35px;
            }

    </style>
</head>
<body>
    <!-- Define header and footer blocks before your content -->
    <header>
        <b>{{ $file_name }}</b>
    </header>

    <footer>
        Report Generated by Software (Datatech BD Ltd. 01304734623)
    </footer>
    <table>
        <tr>
            <td>
                <img src="{{ asset('assets/images/logo.png') }}" alt="Daniyal Logo" style="height: 80px; weight: 80px; margin-right: 25px;">
            </td>
            <td>
                <h3>53, West Agargoan, Sher-e-Bangla Nagar, Dhaka-1207. (Near by Suleman Restaurant)</h3>
                <p>Cell : 01766-777459 , 01754-852774, daniyalfoodcafe@gmail.com , daniyalfood.com.bd</p>
                <br>
            </td>
        </tr>
    </table>
    <br>
    <hr>
    <br>
    @yield('content')
</body>
</html>

